import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'
import Navber from '../components/Navber'

const Blog: NextPage = () => {
  const MainText = '☀ 開発中です！☁'
  const SubText =
    'EpochごとにCardanoのニュースをまとめた「Epoch☀Blog」を発信します。'
  const ButtonLink = 'Wellcome'

  return (
    <div>
      <Head>
        <title>Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navber />
      <Hero MainText={MainText} SubText={SubText} ButtonLink={ButtonLink} />
    </div>
  )
}

export default Blog
