import type { NextPage, InferGetStaticPropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { client } from 'libs/client'
import type { Blog, Tag } from 'types/blog'

export const getStaticProps = async () => {
  const blog = await client.get({
    endpoint: 'blog',
  })
  const tag = await client.get({
    endpoint: 'tag',
  })
  return {
    props: {
      blogs: blog.contents,
      tags: tag.contents,
    },
  }
}

// Props (blogs, tags)の型定義-Arrayとジェネリック型を覚える。
type Props = {
  blogs: Array<Blog>
  tags: Array<Tag>
}

const Blog: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  blogs,
}: Props) => {
  // const MainText = '☀ 開発中☁'
  // const SubText =
  //   'EpochごとにCardanoのニュースをまとめた「Epoch☀Blog」を発信します。'
  // const ButtonLink = 'Wellcome'
  return (
    <div>
      <Head>
        <title>Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {blogs.map((blog) => (
          <li key={blog.id}>
            <Link href={`/blog/${blog.id}`}>
              <a>{blog.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </div>
  )
}
export default Blog
