import type { NextPage } from 'next'
import Head from 'next/head'
import Hero from '../components/Hero'

const Home: NextPage = () => {
  const MainText = 'CIEL Stake Pool'
  const SubText = 'ARMベースで構築された環境にやさしい Staking Pool です。'
  const ButtonLink = 'Wellcome'

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero MainText={MainText} SubText={SubText} ButtonLink={ButtonLink} />
    </>
  )
}

export default Home
